---   
apiVersion: v1 
kind: Namespace
metadata:
  name: __namespace__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __namespace__
  name: deployment-__appname__
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-__appname__
  replicas: __pods__
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-__appname__
    spec:
      containers:
      - image: __imagename__
        imagePullPolicy: Always
        name: app-__appname__
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  namespace: __namespace__
  name: service-__appname__
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-__appname__

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: __namespace__
  name: ingress-__appname__
  annotations:

spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: service-__appname__
                port:
                  number: 80
